---
- hosts: ubuntuRemote
  vars:
    default_container_name: img
    default_container_image: ubuntu
    default_container_command: /bin/bash
    
  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
